# Generated by Django 2.2.5 on 2019-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='otp',
            field=models.IntegerField(default=459),
        ),
    ]
