# Generated by Django 2.2.5 on 2020-01-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(max_length=20)),
                ('leave_reason', models.EmailField(max_length=50)),
            ],
        ),
    ]
