# Generated by Django 2.2.5 on 2020-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_leave',
            name='hr_nm',
            field=models.CharField(default='', max_length=50),
        ),
    ]
