# Generated by Django 2.2.5 on 2020-01-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hr_leave_hr_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_leave',
            name='hr_lv_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
