# Generated by Django 2.2.5 on 2020-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hr_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_leave',
            name='date_end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hr_leave',
            name='date_start',
            field=models.CharField(max_length=30),
        ),
    ]
