# Generated by Django 2.2.5 on 2019-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hr_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('joiningdate', models.DateTimeField()),
                ('phone', models.IntegerField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('pic', models.FileField(default='set.jpg', upload_to='images/')),
            ],
        ),
    ]
