# Generated by Django 2.2.5 on 2020-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hr_leave_hr_lv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_leave',
            name='hr_lv_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
