# Generated by Django 2.2.5 on 2019-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hr_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_emp',
            name='joiningdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hr_emp',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
