# Generated by Django 2.2.5 on 2020-01-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200106_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_leave',
            name='hr_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.HR'),
        ),
    ]
