# Generated by Django 2.2.5 on 2019-11-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191105_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_emp',
            name='phone',
        ),
    ]
