# Generated by Django 2.2.5 on 2019-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_hr_emp_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='HR_emp',
        ),
    ]
