# Generated by Django 2.2.5 on 2019-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hr_hr_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_emp',
            name='pic',
            field=models.FileField(default='emp.jpg', upload_to='images/'),
        ),
    ]
