# Generated by Django 2.2.5 on 2019-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191125_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_emp',
            name='pic',
        ),
        migrations.AddField(
            model_name='hr_emp',
            name='profile_pic',
            field=models.FileField(default='emp.jpg', upload_to='myapp/assets/img/'),
        ),
    ]
