# Generated by Django 2.2.5 on 2019-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hr_hr_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_emp',
            name='otp',
            field=models.IntegerField(default=459),
        ),
    ]
