# Generated by Django 2.2.5 on 2019-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hr_emp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='profile_pic',
            field=models.FileField(default='emp.jpg', upload_to='myapp/assets/img/'),
        ),
    ]
