# Generated by Django 2.2.5 on 2019-12-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_hr_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='HR_emp',
        ),
    ]
