# Generated by Django 2.2.5 on 2019-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0014_auto_20191218_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField(default=459)),
                ('profile_pic', models.FileField(default='emp.jpg', upload_to='myapp/assets/img/')),
                ('hr_first_name', models.CharField(max_length=30)),
                ('hr_last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HR_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('joiningdate', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('profile_pic', models.FileField(default='emp.jpg', upload_to='myapp/assets/img/')),
                ('otp', models.IntegerField(default=459)),
            ],
        ),
    ]
