# Generated by Django 2.2.5 on 2020-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
        migrations.AddField(
            model_name='emp_leaves',
            name='emp_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
