# Generated by Django 2.2.5 on 2020-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_leave_type', models.CharField(max_length=30)),
                ('emp_date_start', models.CharField(max_length=30)),
                ('emp_date_end', models.CharField(max_length=20)),
                ('emp_leave_reason', models.EmailField(max_length=50)),
                ('emp_no_day', models.CharField(max_length=20)),
                ('emp_hr_nm', models.CharField(default='', max_length=50)),
                ('emp_hr_lv_status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
