# Generated by Django 2.2.5 on 2020-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0003_emp_atd'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_atd',
            name='punch_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
