# Generated by Django 2.2.5 on 2020-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0004_emp_atd_punch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_atd',
            name='emp_id',
            field=models.ForeignKey(default='', on_delete='', to='myapp.HR_emp'),
        ),
    ]
