# Generated by Django 2.2.5 on 2020-02-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0005_auto_20200206_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_atd',
            name='punch_type',
            field=models.CharField(default='punch-in', max_length=50),
        ),
    ]
