# Generated by Django 2.2.5 on 2020-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0006_auto_20200206_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_atd',
            name='punch_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
