# Generated by Django 2.2.5 on 2020-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Employee', '0007_auto_20200227_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_atd',
            name='punch_type',
            field=models.CharField(default='punch-in', max_length=50),
        ),
    ]
